/**
 * Runs the crossover end to end and prints a summary.
 *
 * Node 24 strips the types, so this file runs directly:
 *
 * ```sh
 * pnpm --filter @tapedeck/example-sma-crossover start
 * ```
 *
 * Metrics — Sharpe, drawdown, profit factor — arrive with `@tapedeck/report` in phase 2. What is
 * printed here is what the core itself knows, including the warnings, which come first on purpose.
 */

import {
  type RunResult,
  Engine,
  INSTRUMENTS,
  MONEY_EXP,
  PRESETS,
  formatFixed,
  toIso,
} from '@tapedeck/core';
import { smaCrossover, type SmaCrossoverParams } from './strategy.ts';
import { syntheticSeries } from './series.ts';

const BARS = 20_000;
const INITIAL_CASH = '100000';

const params: SmaCrossoverParams = {
  fastPeriod: 20,
  slowPeriod: 60,
  qty: 1,
  allowShort: true,
};

function money(value: number): string {
  return formatFixed(value, MONEY_EXP);
}

function percent(part: number, whole: number): string {
  return whole === 0 ? '0.0%' : `${((part / whole) * 100).toFixed(1)}%`;
}

function summarise(result: RunResult): string {
  const lines: string[] = [];
  const { stats } = result;

  if (result.warnings.length > 0) {
    lines.push('Modelling caveats');
    for (const warning of result.warnings) lines.push(`  ! ${warning}`);
    lines.push('');
  }

  lines.push(`Strategy       ${result.config.strategyId}  seed=${String(result.config.seed)}`);
  lines.push(`Instrument     ${result.config.instruments.join(', ')}`);
  lines.push(
    `Execution      slippage=${result.config.slippageModel}  commission=${result.config.commissionModel}`,
  );
  lines.push(
    `               liquidity=${result.config.liquidityModel}  intrabar=${result.config.intrabarPolicy}`,
  );
  lines.push(
    `Period         ${result.startTs === null ? 'n/a' : toIso(result.startTs)} to ${
      result.endTs === null ? 'n/a' : toIso(result.endTs)
    }`,
  );
  lines.push('');
  lines.push(`Bars           ${String(stats.bars)}`);
  lines.push(
    `Orders         ${String(stats.ordersSubmitted)} submitted, ${String(stats.ordersRejected)} rejected`,
  );
  lines.push(`Fills          ${String(stats.fills)} (${String(stats.partialFills)} partial)`);
  lines.push(`Trades         ${String(result.trades.length)}`);
  lines.push('');
  lines.push(`Initial cash   ${money(result.initialCash)}`);
  lines.push(`Final equity   ${money(result.finalEquity)}`);
  lines.push(`Realised PnL   ${money(result.realizedPnl)}`);
  lines.push(`Unrealised     ${money(result.unrealizedPnl)}`);
  lines.push(`Commission     ${money(result.commissionPaid)}`);

  const wins = result.trades.filter((trade) => trade.netPnl > 0).length;
  lines.push(
    `Win rate       ${percent(wins, result.trades.length)} (${String(wins)}/${String(result.trades.length)})`,
  );

  return lines.join('\n');
}

function main(): void {
  const engine = new Engine<SmaCrossoverParams>({
    instruments: [INSTRUMENTS.WIN],
    strategy: smaCrossover,
    params,
    initialCash: INITIAL_CASH,
    seed: 20260825,
    execution: PRESETS.b3Futures(),
    flattenAtEnd: true,
  });

  const series = syntheticSeries({
    instrument: engine.registry.byId(0 as never),
    bars: BARS,
    startPrice: 130_000,
    seed: 20260825,
  });

  engine.feedBars(series);
  const result = engine.finish();

  console.log('Tapedeck — SMA crossover on SYNTHETIC data (engine smoke test, not a backtest)\n');
  console.log(summarise(result));
  console.log(
    '\nThe prices above were generated by a seeded random walk with a sine drift. A crossover\n' +
      'finds that trivially, so the win rate says nothing about the strategy — only that orders,\n' +
      'fills, costs and accounting all ran end to end. Real data arrives with the adapters.',
  );
}

main();
